---
- hosts: localhost
  connection: local
  vars_files:
    - vars/env.yaml

  roles:
    # - role: gantsign.visual-studio-code

  tasks:
    - name: install packages
      become: true
      become_user: root
      package:
        name:
          - git
          - ripgrep
          - rsync
          - fd-find
          - ansible-lint
          - libfuse2 # for running AppImage files (logseq)
          - bat
          - htop
          - build-essential
        state: present

    - name: Create ~/.local/bin directory
      file:
        path: $HOME/.local/bin
        state: directory
        mode: 0755

    - name: set fdfind path as variable
      command: which fdfind
      register: fdfind_path
      changed_when: false

    - name: Create symlink from fdfind to fd
      file:
        src: "{{ fdfind_path.stdout }}"
        path: $HOME/.local/bin/fd
        state: link

    - name: Create symlink from batcat to bat
      file:
        src: /usr/bin/batcat
        path: $HOME/.local/bin/bat
        state: link

    - name: copy .bashrc file
      copy:
        src: files/.bashrc
        dest: $HOME/.bashrc
        mode: 0644

    - name: copy .bash_aliases file
      copy:
        src: files/.bash_aliases
        dest: $HOME/.bash_aliases
        mode: 0644

    - name: copy .inputrc file
      copy:
        src: files/.inputrc
        dest: $HOME/.inputrc
        mode: 0644

    - name: copy .vimrc file
      copy:
        src: files/.vimrc
        dest: $HOME/.vimrc
        mode: 0644

    - name: copy JetBrainsMono folder
      copy:
        src: files/JetBrainsMono
        dest: $HOME/.local/share/fonts/
        directory_mode: 0755
        mode: 0644

    - name: clone git bash prompt
      git:
        repo: https://github.com/magicmonty/bash-git-prompt.git
        dest: $HOME/.bash-git-prompt
        depth: 1
        version: 2.7.1

    - name: clone goto.sh
      git:
        repo: https://github.com/iridakos/goto.git
        dest: $HOME/.goto
        depth: 1
        version: v2.0.0

    - name: clone fzf
      git:
        repo: https://github.com/junegunn/fzf.git
        dest: $HOME/.fzf
        depth: 1
        version: master

    - name: install fzf
      command: $HOME/.fzf/install
      changed_when: false

    - import_tasks: ./tasks/install_vscode.yml

    - import_tasks: ./tasks/install_chrome.yml

    - import_tasks: ./tasks/install_syncthing.yml

    - import_tasks: ./tasks/install_github-cli.yml

    - import_tasks: ./tasks/install_logseq.yml

    - import_tasks: ./tasks/install_asdf.yml

    - import_tasks: ./tasks/install_node_packages.yml

    - import_tasks: ./tasks/install_dbeaver.yml

    - import_tasks: ./tasks/install_postgresql.yml

    - import_tasks: ./tasks/install_docker.yml

    # - name: copy wallpaper file
    #   copy:
    #     src: files/wallpaper.png
    #     dest: /usr/share/backgrounds/ansible-wallpaper.png
    #     owner: root
    #     group: root
    #     mode: 0644

    # - name: set wallpaper
    #   become_user: jay
    #   dconf:
    #     key: "/org/gnome/desktop/background/picture-uri"
    #     value: "'file:///usr/share/backgrounds/ansible-wallpaper.png'"

    # - name: set wallpaper position
    #   become_user: jay
    #   dconf:
    #     key: "/org/gnome/desktop/background/picture-options"
    #     value: "'zoom'"
