---
- hosts: localhost
  connection: local
  become: true

  tasks:
    - name: install packages
      package:
        name:
          - ripgrep
          - rsync
          # - asdf
          # - postgres
          # - elixir/erlang
          # - nodejs

      # apt: name=ripgrep
