---
- hosts: localhost
  connection: local

  tasks:
    - name: install packages
      become: true
      become_user: root
      package:
        name:
          - ripgrep
          - rsync
          - fzf
          - fd-find
        # - asdf
        # - postgres
        # - elixir/erlang
        # - nodejs

    - name: Create ~/.local/bin directory
      file:
        path: $HOME/.local/bin
        state: directory

    - name: set fdfind path as variable
      command: which fdfind
      register: fdfind_path
    - name: Create symlink from fdfind to fd
      file:
        src: "{{ fdfind_path.stdout }}"
        path: $HOME/.local/bin/fd
        state: link
    # - name: Create symlink from fdfind to fd
    #   ansible.builtin.shell: ln -s $(which fdfind) ~/.local/bin/fd
    #   ignore_errors: true

    - name: copy .bashrc file
      copy:
        src: files/.bashrc
        dest: $HOME/.bashrc

    # - name: copy wallpaper file
    #   copy:
    #     src: files/wallpaper.png
    #     dest: /usr/share/backgrounds/ansible-wallpaper.png
    #     owner: root
    #     group: root
    #     mode: 0644

    # - name: set wallpaper
    #   become_user: jay
    #   dconf:
    #     key: "/org/gnome/desktop/background/picture-uri"
    #     value: "'file:///usr/share/backgrounds/ansible-wallpaper.png'"

    # - name: set wallpaper position
    #   become_user: jay
    #   dconf:
    #     key: "/org/gnome/desktop/background/picture-options"
    #     value: "'zoom'"
