- name: Add syncthing apt signing key
  become: true
  ansible.builtin.apt_key:
    url: https://syncthing.net/release-key.gpg
    keyring: /usr/share/keyrings/syncthing-archive-keyring.gpg
    state: present
- name: Add repository into sources list
  become: true
  ansible.builtin.apt_repository:
    repo: deb [signed-by=/usr/share/keyrings/syncthing-archive-keyring.gpg] https://apt.syncthing.net/ syncthing stable
    state: present
    filename: syncthing
- name: Install syncthing
  become: true
  ansible.builtin.apt:
    name: syncthing
    state: present
    update_cache: true
- name: Start and enable systemd service
  ansible.builtin.systemd:
    name: syncthing
    enabled: true
    state: started
    scope: user
