- name: install/update logseq
  ansible.builtin.shell: gh release download -R logseq/logseq -p '*.AppImage' -O ~/.local/bin/logseq --clobber
  environment:
    GH_TOKEN: "{{ github_token }}"
  changed_when: false

- name: make logseq executable
  ansible.builtin.file:
    path: ~/.local/bin/logseq
    mode: 0744
  tags:
    - tag1

- name: copy .desktop file
  ansible.builtin.copy:
    src: ../files/logseq.desktop
    dest: $HOME/.local/share/applications/logseq.desktop
    mode: 0644
  # tags:
  #   - tag1

- name: replace home dir in .desktop file
  ansible.builtin.replace:
    path: $HOME/.local/share/applications/logseq.desktop
    regexp: '\$HOME'
    replace: "/home/{{ os_user }}"
  # tags:
  #   - tag1

- name: create .logseq directory
  ansible.builtin.file:
    path: $HOME/.logseq
    state: directory
    mode: 0775
  # tags:
  #   - tag1

- name: copy logseq icon file
  ansible.builtin.copy:
    src: ../files/logseq_icon.png
    dest: $HOME/.logseq/logseq_icon.png
    mode: 0644
  # tags:
  #   - tag1
