# - name: Install apt-transport-https
#   become: true
#   ansible.builtin.apt:
#     name: apt-transport-https
#     state: present
#     update_cache: true
- name: Add github apt signing key
  become: true
  ansible.builtin.apt_key:
    url: "https://cli.github.com/packages/githubcli-archive-keyring.gpg"
    keyring: /usr/share/keyrings/githubcli-archive-keyring.gpg
    state: present
- name: Add repository into sources list
  become: true
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64 signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main
    state: present
    filename: github-cli
- name: Install github-cli
  become: true
  ansible.builtin.apt:
    name: gh
    state: present
    update_cache: true
