- name: install jdk
  become: true
  become_user: root
  package:
    name: default-jdk
    state: present

- name: Add dbeaver apt signing key
  become: true
  ansible.builtin.get_url:
    url: https://dbeaver.io/debs/dbeaver.gpg.key
    dest: /etc/apt/keyrings/dbeaver.asc
    mode: '0644'
    force: true
- name: Add repository into sources list
  become: true
  ansible.builtin.apt_repository:
    repo: deb [signed-by=/etc/apt/keyrings/dbeaver.asc] https://dbeaver.io/debs/dbeaver-ce /
    state: present
    filename: dbeaver
- name: Install dbeaver-ce
  become: true
  ansible.builtin.apt:
    name: dbeaver-ce
    state: present
    update_cache: true