# - name: Install apt-transport-https
#   become: true
#   ansible.builtin.apt:
#     name: apt-transport-https
#     state: present
#     update_cache: true
- name: Add postgres apt signing key
  become: true
  ansible.builtin.get_url:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    dest: /etc/apt/keyrings/postgresql.asc
    mode: '0644'
    force: true
- name: Add repository into sources list
  become: true
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64 signed-by=/etc/apt/keyrings/postgresql.asc] http://apt.postgresql.org/pub/repos/apt {{ ansible_distribution_release }}-pgdg main
    state: present
    filename: pgdg
- name: Install latest postgresql
  become: true
  ansible.builtin.apt:
    name: postgresql
    state: present
    update_cache: true
