- name: Add syncthing apt signing key
  become: true
  ansible.builtin.get_url:
    url: https://syncthing.net/release-key.gpg
    dest: /etc/apt/keyrings/syncthing.gpg
    mode: '0644'
    force: true
- name: Add repository into sources list
  become: true
  ansible.builtin.apt_repository:
    repo: deb [signed-by=/etc/apt/keyrings/syncthing.gpg] https://apt.syncthing.net/ syncthing stable
    state: present
    filename: syncthing
- name: Install syncthing
  become: true
  ansible.builtin.apt:
    name: syncthing
    state: present
    update_cache: true
- name: Start and enable systemd service
  ansible.builtin.systemd:
    name: syncthing
    enabled: true
    state: started
    scope: user
